# Generated by Django 3.2.6 on 2021-08-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=500)),
                ('op2', models.CharField(max_length=500)),
                ('op3', models.CharField(max_length=500)),
                ('op4', models.CharField(max_length=500)),
                ('test_answer', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'quizes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.user')),
            ],
        ),
        migrations.CreateModel(
            name='TakeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='TakeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_answer_taken', models.PositiveSmallIntegerField()),
                ('date_answered', models.DateTimeField()),
                ('correct_answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.question')),
                ('take_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.takequiz')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.subject'),
        ),
    ]
